SHELL := bash
.SHELLFLAGS := -eu -o pipefail -c
.DEFAULT_GOAL := verify

UV ?= uv
RUN := $(UV) run --frozen
TOOLS_BIN := $(shell $(RUN) python -c "from tools.install import target_dir; print(target_dir())" 2>/dev/null || echo .tools/bin/unknown)
export PATH := $(CURDIR)/$(TOOLS_BIN):$(PATH)
CI_IMAGE := python:3.12.14-slim
WORKDIR_HOST := $(shell pwd -W 2>/dev/null || pwd)
GIT_COMMON_HOST := $(shell cd "$$(git rev-parse --git-common-dir)" && (pwd -W 2>/dev/null || pwd))
GIT_DIR_REL := $(shell $(RUN) python -c "import os,sys; print(os.path.relpath(sys.argv[1], sys.argv[2]).replace(chr(92), chr(47)))" "$$(git rev-parse --absolute-git-dir)" "$$(git rev-parse --git-common-dir)")

.PHONY: budgets-check coverage-check image image-scan tools hooks fmt lint api api-check ledgers-check test storage evals security selftest verify verify-fast ci serve worker migrate check record new-capability clean

tools:
	$(UV) sync --frozen --group dev
	$(RUN) python -m tools.install

hooks:
	git config core.hooksPath .githooks
	@echo "hooks: core.hooksPath -> .githooks"

fmt:
	$(RUN) ruff format src tests tools

lint:
	$(RUN) ruff format --check src tests tools
	$(RUN) ruff check src tests tools
	$(RUN) mypy src tools tests
	@for set in evals/*/graders.py; do $(RUN) mypy "$$set" || exit 1; done
	$(RUN) lint-imports
	$(RUN) python -m tools.checks.gate --skip coverage,budgets

lint-fast:
	$(RUN) ruff format --check src tests tools
	$(RUN) ruff check src tests tools
	$(RUN) mypy src tools tests
	$(RUN) python -m tools.checks.gate --fast

api:
	$(RUN) python -m tools.api --write

api-check:
	$(RUN) python -m tools.api
	@if git rev-parse --verify --quiet main >/dev/null && git cat-file -e main:api/openapi.yaml 2>/dev/null; then git show main:api/openapi.yaml > .tools/openapi.main.yaml && oasdiff breaking .tools/openapi.main.yaml api/openapi.yaml --fail-on ERR && echo "oasdiff: no breaking change against main"; else echo "oasdiff: no main document yet, nothing to compare"; fi

ledgers-check:
	@echo "ledgers: generated by hand until make ledgers exists (docs/04-ledgers/README.md); drift is a finding"

test:
	$(RUN) pytest tests/architecture -q
	$(RUN) pytest --cov --cov-report=term-missing --cov-report=json:coverage.json --cov-fail-under=90

storage:
	$(RUN) pytest tests/storage -q

evals:
	@if ls evals/*/set.jsonl >/dev/null 2>&1; then $(RUN) python -m tools.evals; else echo "evals: no eval set yet, nothing to run"; fi

security:
	$(UV) export --frozen --no-emit-project --quiet -o .tools/requirements.txt
	$(RUN) pip-audit --strict --progress-spinner off --disable-pip -r .tools/requirements.txt
	gitleaks git --no-banner --redact .
	$(RUN) python -m tools.checks.gate --only licenses

selftest:
	$(RUN) python -m tools.checks.selftest

coverage-check:
	$(RUN) python -m tools.checks.gate --only coverage

verify: lint api-check ledgers-check test coverage-check storage evals budgets-check security selftest
	@echo "VERIFY GREEN"

verify-fast: lint-fast
	gitleaks protect --staged --no-banner --redact
	@echo "VERIFY-FAST GREEN"

ci:
	MSYS_NO_PATHCONV=1 docker run --rm -t \
		-v "$(WORKDIR_HOST)":/work -w /work \
		-v /var/run/docker.sock:/var/run/docker.sock -e TESTCONTAINERS_RYUK_DISABLED=true \
		-v "$(GIT_COMMON_HOST)":/gitcommon -e GIT_DIR=/gitcommon/$(GIT_DIR_REL) -e GIT_WORK_TREE=/work \
		-e HOME=/tmp -e UV_CACHE_DIR=/tmp/uv-cache -e UV_PROJECT_ENVIRONMENT=/tmp/venv -e UV_LINK_MODE=copy \
		$(CI_IMAGE) bash -c "$$($(RUN) python -m tools.ci_steps)"

serve:
	$(RUN) catalyst-ai serve

worker:
	$(RUN) catalyst-ai worker

migrate:
	$(RUN) catalyst-ai migrate

check:
	$(RUN) catalyst-ai check

record:
	$(RUN) python -m tools.record --set $(or $(CAP),improve-story) $(if $(LIVE),--live,--authored)

new-capability:
	@echo "new-capability: built with the golden capability"; exit 1

clean:
	rm -rf .pytest_cache .mypy_cache .ruff_cache coverage.json .coverage

image:
	docker build -t catalyst-ai:local .

image-scan: image
	trivy image --scanners vuln --severity HIGH,CRITICAL --ignore-unfixed --exit-code 1 --no-progress --skip-version-check catalyst-ai:local

budgets-check:
	$(RUN) python -m tools.checks.gate --only budgets
