SHELL := bash
.SHELLFLAGS := -eu -o pipefail -c
.DEFAULT_GOAL := verify

# `uv run` exports UV as its own path; on Windows a recipe would mangle it. Only the command line
# (make UV=...) may name another uv, never an inherited environment variable.
UV := uv
RUN := $(UV) run --frozen
TOOLS_BIN := $(shell $(RUN) python -c "from tools.install import target_dir; print(target_dir())" 2>/dev/null || echo .tools/bin/unknown)
export PATH := $(CURDIR)/$(TOOLS_BIN):$(PATH)
CI_IMAGE := python:3.12.14-slim@sha256:2f17fc044b579bab302c2e8054d3a686e2cb9a83de48e70534b94cd8ebbe06a9
CI_LOCAL_IMAGE = $(shell $(RUN) python -m tools.ci_image tag)
CI_UV_OFFLINE ?= 1
CI_VOLUMES := -v catalyst-ai-ci-uv:/tmp/uv-cache -v catalyst-ai-ci-venv:/tmp/venv -v catalyst-ai-ci-cache:/tmp/.cache
CI_CACHES := -e RUFF_CACHE_DIR=/tmp/.cache/ruff -e MYPY_CACHE_DIR=/tmp/.cache/mypy -e HYPOTHESIS_STORAGE_DIRECTORY=/tmp/.cache/hypothesis
PYTEST_ITERATE := --import-mode=importlib --disable-socket --allow-hosts=127.0.0.1,::1 --strict-markers -q
WORKDIR_HOST := $(shell pwd -W 2>/dev/null || pwd)
GIT_COMMON_HOST := $(shell cd "$$(git rev-parse --git-common-dir)" && (pwd -W 2>/dev/null || pwd))
GIT_DIR_REL := $(shell $(RUN) python -c "import os,sys; print(os.path.relpath(sys.argv[1], sys.argv[2]).replace(chr(92), chr(47)))" "$$(git rev-parse --absolute-git-dir)" "$$(git rev-parse --git-common-dir)")
# The image reads git and never writes it: the common directory is mounted read-only and git takes
# no optional lock, so nothing a step runs in there can change the repository's config or index.
# The stamp is written on the host, after the container has exited.
CI_GIT = -v "$(GIT_COMMON_HOST)":/gitcommon:ro -e GIT_DIR=/gitcommon/$(GIT_DIR_REL) \
	-e GIT_WORK_TREE=/work -e GIT_OPTIONAL_LOCKS=0

.PHONY: budgets-check coverage-check image image-scan scan-tools tools hooks fmt lint api api-check ledgers-check test test-fast storage drill drills load nightly nightly-fuzz nightly-repeat evals evals-affected security selftest verify verify-fast verify-docs verify-checks ci ci-scoped ci-aware ci-cold ci-image ci-image-push stamp-check release alert-policies serve worker migrate check record new-capability clean

tools:
	$(UV) sync --frozen --group dev
	$(RUN) python -m tools.install

hooks:
	@test "$$(git config --get core.hooksPath)" = ".githooks" || git config core.hooksPath .githooks
	@echo "hooks: core.hooksPath -> .githooks"

fmt:
	$(RUN) ruff format src tests tools

lint:
	$(RUN) ruff format --check src tests tools
	$(RUN) ruff check src tests tools
	$(RUN) mypy src tools tests
	@for set in evals/*/graders.py; do $(RUN) mypy "$$set" || exit 1; done
	$(RUN) lint-imports
	$(RUN) python -m tools.checks.gate --skip coverage,budgets

lint-fast:
	$(RUN) ruff format --check src tests tools
	$(RUN) ruff check src tests tools
	$(RUN) mypy src tools tests
	$(RUN) python -m tools.checks.gate --fast

api:
	$(RUN) python -m tools.api --write

api-check:
	$(RUN) python -m tools.api
	@if git rev-parse --verify --quiet main >/dev/null && git cat-file -e main:api/openapi.yaml 2>/dev/null; then git show main:api/openapi.yaml > .tools/openapi.main.yaml && oasdiff breaking .tools/openapi.main.yaml api/openapi.yaml --fail-on ERR && echo "oasdiff: no breaking change against main"; else echo "oasdiff: no main document yet, nothing to compare"; fi

ledgers-check:
	@echo "ledgers: generated by hand until make ledgers exists (docs/04-ledgers/README.md); drift is a finding"

test:
	$(RUN) pytest tests/architecture -q
	$(RUN) pytest --cov --cov-report=term-missing --cov-report=json:coverage.json --cov-fail-under=90

test-fast:
	$(RUN) pytest tests/unit -o addopts="$(PYTEST_ITERATE)" --lf --ff -x

storage:
	$(RUN) pytest tests/storage -q

drill:
	$(RUN) python -m tools.drill --capability $(CAP)

drills:
	$(RUN) python -m tools.drill --capability summarize
	$(RUN) python -m tools.drill --capability improve-story

load:
	$(RUN) python -m tools.load --concurrency $(or $(N),16) --rounds $(or $(ROUNDS),4)

nightly-fuzz:
	$(RUN) pytest tests/unit/retrieval/parsers tests/unit/retrieval/test_chunking_property.py -k property --hypothesis-profile=nightly

nightly-repeat:
	@for run in $$(seq $(or $(REPEATS),5)); do echo "nightly-repeat: storage run $$run of $(or $(REPEATS),5)"; $(RUN) pytest tests/storage -q || exit 1; done

nightly: nightly-fuzz nightly-repeat
	$(MAKE) --no-print-directory load N=64 ROUNDS=16
	@echo "NIGHTLY GREEN"

evals:
	@if ls evals/*/set.jsonl >/dev/null 2>&1; then $(RUN) python -m tools.evals; else echo "evals: no eval set yet, nothing to run"; fi

evals-affected:
	@if ls evals/*/set.jsonl >/dev/null 2>&1; then $(RUN) python -m tools.evals --affected; else echo "evals: no eval set yet, nothing to run"; fi

security:
	$(UV) export --frozen --no-emit-project --quiet -o .tools/requirements.txt
	$(RUN) pip-audit --strict --progress-spinner off --disable-pip -r .tools/requirements.txt
	gitleaks git --no-banner --redact .
	$(RUN) python -m tools.checks.gate --only licenses

selftest:
	$(RUN) python -m tools.checks.selftest

coverage-check:
	$(RUN) python -m tools.checks.gate --only coverage

verify: lint api-check ledgers-check test coverage-check storage drills evals budgets-check security selftest
	@echo "VERIFY GREEN"

verify-docs:
	$(RUN) python -m tools.checks.gate --skip coverage,budgets
	$(RUN) python -m tools.checks.selftest
	gitleaks git --no-banner --redact .
	@echo "VERIFY-DOCS GREEN"

verify-checks:
	$(RUN) ruff format --check src tests tools
	$(RUN) ruff check src tests tools
	$(RUN) mypy src tools tests
	$(RUN) pytest tests/unit/tools
	$(MAKE) --no-print-directory verify-docs
	@echo "VERIFY-CHECKS GREEN"

verify-fast: lint-fast evals-affected
	gitleaks protect --staged --no-banner --redact
	@echo "VERIFY-FAST GREEN (iteration, not evidence: make ci is the evidence)"

ci:
	@$(RUN) python -m tools.ci_image require
	$(RUN) python -m tools.stamp begin
	$(RUN) python -m tools.ci_postgres up
	status=0; MSYS_NO_PATHCONV=1 docker run --rm -t $$($(RUN) python -m tools.ci_postgres args) \
		-v "$(WORKDIR_HOST)":/work -w /work $(CI_VOLUMES) $(CI_CACHES) \
		$(CI_GIT) \
		-e HOME=/tmp -e UV_CACHE_DIR=/tmp/uv-cache -e UV_PROJECT_ENVIRONMENT=/tmp/venv -e UV_LINK_MODE=copy \
		-e UV_OFFLINE=$(CI_UV_OFFLINE) $(CI_LOCAL_IMAGE) bash -c "$$($(RUN) python -m tools.ci_steps --prebuilt)" || status=$$?; \
	$(RUN) python -m tools.ci_postgres down; exit $$status
	$(RUN) python -m tools.stamp write --image $(CI_LOCAL_IMAGE)

ci-scoped:
	@$(RUN) python -m tools.ci_image require
	$(RUN) python -m tools.stamp begin
	MSYS_NO_PATHCONV=1 docker run --rm -t \
		-v "$(WORKDIR_HOST)":/work -w /work $(CI_VOLUMES) $(CI_CACHES) \
		$(CI_GIT) \
		-e HOME=/tmp -e UV_CACHE_DIR=/tmp/uv-cache -e UV_PROJECT_ENVIRONMENT=/tmp/venv -e UV_LINK_MODE=copy \
		-e UV_OFFLINE=$(CI_UV_OFFLINE) $(CI_LOCAL_IMAGE) bash -c "make tools && make $(TARGETS)"
	$(RUN) python -m tools.stamp write --image $(CI_LOCAL_IMAGE) --scope $(SCOPE)

ci-aware:
	$(RUN) python -m tools.change_gate --run

ci-cold:
	-docker volume rm catalyst-ai-ci-uv catalyst-ai-ci-venv catalyst-ai-ci-cache
	$(MAKE) --no-print-directory ci CI_UV_OFFLINE=0

ci-image:
	$(RUN) python -m tools.ci_image build

ci-image-push:
	$(RUN) python -m tools.ci_image push

stamp-check:
	@$(RUN) python -m tools.stamp check --image $(CI_LOCAL_IMAGE)

release:
	$(RUN) python -m tools.release $(RELEASE_FLAGS)

# Print, never run: the command that turns ops/alerts.yaml into Cloud Monitoring alerting policies,
# names and thresholds unchanged, once the metrics sidecar writes the numbers (the lead runs it).
alert-policies:
	@echo gcloud monitoring policies migrate --policies-from-prometheus-alert-rules-yaml=ops/alerts.yaml

serve:
	$(RUN) catalyst-ai serve

worker:
	$(RUN) catalyst-ai worker

migrate:
	$(RUN) catalyst-ai migrate

check:
	$(RUN) catalyst-ai check

record:
	$(RUN) python -m tools.record --set $(or $(CAP),improve-story) $(if $(LIVE),--live,--authored)

new-capability:
	@echo "new-capability: built with the golden capability"; exit 1

clean:
	rm -rf .pytest_cache .mypy_cache .ruff_cache coverage.json .coverage

image:
	docker build -t catalyst-ai:local .

scan-tools:
	$(RUN) python -m tools.install --scan

image-scan: image scan-tools
	trivy image --scanners vuln --severity HIGH,CRITICAL --ignore-unfixed --exit-code 1 --no-progress --skip-version-check catalyst-ai:local; \
	status=$$?; trivy version; exit $$status

budgets-check:
	$(RUN) python -m tools.checks.gate --only budgets
