[pytest]
testpaths = tests
pythonpath = . src
asyncio_mode = auto
addopts = -p no:cacheprovider --import-mode=importlib --disable-socket --allow-hosts=127.0.0.1,::1 --strict-markers -q
filterwarnings = error
    ignore:The @wait_container_is_ready decorator is deprecated:DeprecationWarning
